config/routes.rb
Rails.application.routes.draw do

  root 'products#index'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :purchases, only: [:index, :show] do
    post 'abandoned', on: :collection
    post 'notification', on: :collection
  end

  resources :products do
    resources :purchases, only: [:new, :create]
  end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  before_action :authenticate_user!, except: [:notification, :abandoned]
  before_action :set_product, only: [:new, :create]
  before_action :set_purchase, only: [:show, :update, :destroy]

  # Ignorar validação contra ataque CSRF, pois o pagseguro não envia a token
  skip_before_action :verify_authenticity_token 

  # GET /purchases
  # GET /purchases.json
  def index    
    @is_sales = params[:mode] == 'sales'
    if @is_sales
      @items = Product.where(user_id: current_user.id) 
    else 
      @items = current_user.purchases
    end
  end

  # GET /purchases/1
  # GET /purchases/1.json
  def show
    raise Http404 if @purchase.user != current_user
  end

  # GET /purchases/new
  def new
    @purchase = Purchase.new(product: @product)
  end

  # POST /purchases/abandoned
  def abandoned
    Rails.logger.info %Q(
      Requisição recebida de compra abandonada: 
        [notificationCode: #{params[:notificationCode]}] 
      )
    response = PagSeguroService.notification_info(params[:notificationCode])

    purchase = Purchase.find_by token: response[:token]
    purchase.status = response[:status]
    purchase.save
    Rails.logger.info "Compra abandonada: #{purchase.product.name} - #{response.transaction.reference}"
    render :nothing => true, :status => 200, :content_type => 'text/html'    
  end

  # POST /purchases/notification
  def notification
    Rails.logger.info %Q(
      Requisição recebida de compra concluída: 
        [notificationCode: #{params[:notificationCode]}] 
      )
    
    response = PagSeguroService.notification_info(params[:notificationCode])
    purchase = Purchase.find_by token: response[:token]
    purchase.status = response[:status]
    purchase.save
    Rails.logger.info "Compra efetuada: #{purchase.product.name} - #{purchase.token}"
    render :nothing => true, :status => 200, :content_type => 'text/html'
  end

  # POST /purchases
  # POST /purchases.json
  def create
    @purchase = Purchase.new(product: @product, user: current_user)
    @purchase.token = SecureRandom.hex
    
    urls = {
      :abandoned => abandoned_purchases_url,
      :notification => notification_purchases_url,
      :redirect => purchases_url
    }

    puts "urls", urls

    if @purchase.save
      response = PagSeguroService.create_payment_request(@purchase, current_user, urls)
      if response.errors.empty?
        redirect_to response.url
      else
        render :new, notice: response.errors.join("\n")
      end
    else
      render :new
    end
  end

  # PATCH/PUT /purchases/1
  # PATCH/PUT /purchases/1.json
  def update
    respond_to do |format|
      if @purchase.update(purchase_params)
        format.html { redirect_to @purchase, notice: 'Purchase was successfully updated.' }
        format.json { render :show, status: :ok, location: @purchase }
      else
        format.html { render :edit }
        format.json { render json: @purchase.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /purchases/1
  # DELETE /purchases/1.json
  def destroy
    @purchase.destroy
    respond_to do |format|
      format.html { redirect_to purchases_url, notice: 'Purchase was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find_by(slug: params[:product_id]) || Product.find(params[:product_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_purchase
      @purchase = Purchase.find(params[:id])
    end
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/views/purchases/_form.html.slim
= simple_form_for(@purchase, url: product_purchases_path(@product.slug)) do |f|
  = f.error_notification
  = button_tag(type: 'submit', class: "button success") do 
      i.fi.fi-check
      =" Confirmar a Compra"

app/views/purchases/edit.html.slim
h1 Editing purchase

== render 'form'

= link_to 'Show', @purchase
'|
= link_to 'Back', purchases_path

app/views/purchases/index.html.slim
= render 'layouts/header'
section.app-content.row
  section.small-3.columns.left-side
    .box
      .box-header
        i.fi-torso 
        = " #{current_user.email}"
      .box-content
        ul.side-nav.inner-nav
          li class=('active' if not @is_sales)
            a href="/purchases?mode=purchases"
              i.fi-shopping-bag 
              = " Minhas Comprinhas"
          li class=('active' if @is_sales)
            a href="/purchases?mode=sales"
              i.fi-pricetag-multiple 
              = " Minhas Vendinhas"
          li
            a = link_to new_product_path
              i.fi-plus 
              = " Vender no #TáNovinho"

  section.small-9.columns.right-side
    .product-listed
      - @items.each do |item|  
        - product = @is_sales ? item : item.product
        .row
          .small-3.columns
            .product-image style="background-image: url(#{attachment_url(product, :product_image, :fill, 1024, 768, format: 'jpg')})"
          .small-9.columns.product-data
            .product-name
              h5
                = product.name
            ul.product-details
              li
                a 
                i.fi-clock 
                = @is_sales ? 'Colocado à venda em ' : 'Comprado em '
                span.date = localize item.created_at, format: :short
              li 
                i.fi-price-tag 
                = number_to_currency product.price
            - if @is_sales
              ul.product-actions 
                = link_to edit_product_path(product), class: 'button secondary left' do
                  i.fi-pencil
                  = " Alterar meu produto"
                = link_to product_path(product), {class: 'button alert left', method: :delete} do
                  i.fi-x
                  = " Remover"

app/views/purchases/new.html.slim
== render "layouts/header"
section.app-content.row
  .small-10.columns.small-centered
    .box.form.checkout
      .box-header
        h4 
          i.fi.fi-check.ta-novinho
          =" Confirme a sua compra"
      .box-content
        .row
          .small-3.columns
            img src="#{attachment_url(@purchase.product, :product_image, :fill, 1024, 768, format: 'jpg')}"
          .small-9.columns
            h3 = @purchase.product.name
            .checkout-description
              = @purchase.product.description
        
            h5 
              span Preço: 
              big.ta-novinho = " #{number_to_currency @purchase.product.price}" 
      .form-actions.box-footer
        == render 'form'

app/views/purchases/show.html.slim
p#notice = notice

p
  strong User:
  = @purchase.user.email
p
  strong Value:
  = @purchase.value

p
  strong Status:
  = @purchase.status

= link_to 'Back', purchases_path